build_from:
  amd64: ghcr.io/home-assistant/amd64-base:3.24-2026.06.1@sha256:2b60b12b34ccd960fda082d223b40dbb2b0bb40af95f12912233b736f27fc47a
  aarch64: ghcr.io/home-assistant/aarch64-base:3.24-2026.06.1@sha256:2ac8f73090063ac23e63a1adc144bd1d8aa88f5e5d92c68898102e81046084a4
labels:
  org.opencontainers.image.title: ha-reverse-autossh-tunnel
  org.opencontainers.image.description: Persistent reverse SSH tunnel for Home Assistant
  org.opencontainers.image.source: https://github.com/micschr0/ha-reverse-autossh-tunnel
  org.opencontainers.image.licenses: MIT
