name: SSH Reverse Tunnel (autossh)
version: 1.4.0
slug: autossh
description: >-
  Persistent reverse SSH tunnel for exposing Home Assistant through a remote
  server
url: https://github.com/micschr0/ha-reverse-autossh-tunnel
image: ghcr.io/micschr0/{arch}-autossh
arch:
  - amd64
  - aarch64
homeassistant: 2024.1.0
startup: application
boot: auto
init: false
host_network: false
privileged: false
host_pid: false
host_ipc: false
options:
  hostname: ''
  ssh_port: 22
  username: autossh
  remote_ip_address: 127.0.0.1
  remote_port: 8123
  other_ssh_options: ''
  monitoring_port: 20000
  force_keygen: false
  skip_remote_host_checks: false
schema:
  hostname: str
  ssh_port: port
  username: str
  remote_ip_address: str
  remote_port: port
  local_ip_address: str?
  local_port: port?
  other_ssh_options: str
  monitoring_port: int(0,65535)
  force_keygen: bool
  skip_remote_host_checks: bool
